
FIND_PATH(LZ4_INCLUDE_DIR lz4.h)
FIND_LIBRARY(LZ4_LIBRARY lz4)

IF(LZ4_LIBRARY AND LZ4_INCLUDE_DIR)
    SET(LZ4_LIBS ${LZ4_LIBRARY})
    SET(LZ4_FOUND "YES")
ELSE()
    SET(LZ4_FOUND "NO")
ENDIF()

IF(LZ4_FOUND)
   IF(NOT LZ4_FIND_QUIETLY)
      MESSAGE(STATUS "Found LZ4: ${LZ4_LIBS}")
   ENDIF()
ELSE()
   IF(LZ4_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find LZ4 library")
   ENDIF()
ENDIF()


MARK_AS_ADVANCED(
  LZ4_LIBRARY
  LZ4_INCLUDE_DIR
  )

